# Stage 1: Build stage
FROM maven:3.8.5-openjdk-17 AS build

WORKDIR /app

# Create the .mvn/wrapper directory and add maven-wrapper.properties
RUN mkdir -p .mvn/wrapper
RUN echo 'distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.5/apache-maven-3.8.5-bin.zip' > .mvn/wrapper/maven-wrapper.properties

# Copy only the necessary files to run mvnw and resolve dependencies
COPY mvnw pom.xml ./

# Download dependencies (will be cached if no changes in pom.xml)
RUN ./mvnw dependency:go-offline

# Copy the rest of the source code and build the project
COPY src src

# Install the Spring Boot dev tools
RUN ./mvnw clean install

# Stage 2: Run stage
FROM openjdk:17.0.1

WORKDIR /app

# Copy the dependencies and build artifacts from the build stage
COPY --from=build /root/.m2 /root/.m2
COPY --from=build /app /app

# Expose the port Spring Boot runs on
EXPOSE 8080

# Set environment variables
ENV JAVA_OPTS=""
ENV SPRING_PROFILES_ACTIVE=dev

# Command to run the application
CMD ["./mvnw", "spring-boot:run"]
